# Generated by Django 3.0.5 on 2021-01-19 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitaldb', '0006_auto_20210119_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_for', models.CharField(blank=True, max_length=500)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('appointment_end_time', models.TimeField(blank=True, null=True)),
                ('appointment_state', models.CharField(choices=[('RE', 'Requested'), ('AC', 'Accepted'), ('DE', 'Declined')], default=('RE', 'Requested'), max_length=2)),
                ('appointment_status', models.CharField(choices=[('DU', 'Due'), ('TK', 'Taken')], default=('DU', 'Due'), max_length=2)),
                ('booking_channel', models.CharField(choices=[('OP', 'On App'), ('OC', 'On Call')], default=('OP', 'On App'), max_length=2)),
                ('appointment_id', models.CharField(max_length=7, unique=True)),
                ('booked_doctor_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.DoctorOffice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prep_nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitaldb.Nurse')),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
            managers=[
                ('booked_appointments', django.db.models.manager.Manager()),
            ],
        ),
    ]
