# Generated by Django 3.0.5 on 2021-01-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210121_1626'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
            ],
        ),
    ]
