# Generated by Django 3.0.5 on 2021-01-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20210125_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
