# Generated by Django 3.0.5 on 2021-01-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20210126_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_rej_reason',
            field=models.CharField(blank=True, max_length=450, verbose_name="Doctor's Reason for Frejecting Appointment"),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
