# Generated by Django 3.0.5 on 2021-01-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20210126_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='short_note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
