# Generated by Django 3.0.5 on 2021-01-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointment_short_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_rej_reason',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_dec_reason',
            field=models.CharField(blank=True, max_length=450, verbose_name="Doctor's Reason for Declining Appointment"),
        ),
    ]
