# Generated by Django 3.0.5 on 2021-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20210126_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_state',
            field=models.CharField(choices=[('RE', 'Requested'), ('AC', 'Accepted'), ('DE', 'Declined')], default=('RE', 'Requested'), max_length=8),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('DU', 'Due'), ('TK', 'Taken')], default=('DU', 'Due'), max_length=8),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_channel',
            field=models.CharField(choices=[('OP', 'On App'), ('OC', 'On Call')], default=('OP', 'On App'), max_length=8),
        ),
    ]
