# Generated by Django 3.0.5 on 2021-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_auto_20210206_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
