# Generated by Django 3.0.5 on 2021-03-22 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0012_auto_20210125_0704'),
        ('appointment', '0017_auto_20210322_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booked_doctor_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospitaldb.DoctorOffice'),
        ),
    ]
