# Generated by Django 3.0.5 on 2021-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_auto_20210322_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
