# Generated by Django 3.0.5 on 2021-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_appointment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
