# Generated by Django 3.2 on 2021-04-20 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_floor', models.IntegerField()),
                ('block_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=400)),
                ('first_consultation_fee', models.FloatField()),
                ('follow_up_cons_fee', models.FloatField()),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': "Doctor's Office",
                'verbose_name_plural': 'Doctor Offices',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter hospital name', max_length=300)),
                ('address', models.CharField(help_text='hospital address', max_length=450)),
                ('hospital_type', models.CharField(choices=[('SC', 'Special Clinic'), ('TH', 'Tranditional Hospital')], default=('TH', 'Tranditional Hospital'), max_length=30)),
                ('rank', models.FloatField(max_length=5)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(blank=True, max_length=250)),
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('AV', 'Available'), ('UA', 'Unavailable')], max_length=15)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitaldb.block')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.hospital')),
            ],
            options={
                'verbose_name': 'Hospital Room',
                'verbose_name_plural': 'Hospital Rooms',
                'ordering': ['availability'],
            },
        ),
        migrations.CreateModel(
            name='OfficeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_available', models.DateField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('AV', 'Available'), ('UA', 'Unavailable')], default=('AV', 'Available'), max_length=2)),
                ('reason_for_unavailability', models.CharField(blank=True, max_length=2000)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.doctoroffice')),
            ],
            options={
                'verbose_name': "Doctor's Schedule",
                'verbose_name_plural': 'Doctors Schedule',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('nurse_id', models.CharField(max_length=7, unique=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('em_cont_name', models.CharField(max_length=150, verbose_name='Emergency Contact Name')),
                ('em_cont_hm_ph', models.CharField(max_length=20, verbose_name='Emergency Conatact Home Phone')),
                ('em_cont_add', models.CharField(max_length=250, verbose_name='Emergency Contact Address')),
                ('em_cont_wrk_ph', models.CharField(max_length=250, verbose_name='Emergency Contact Work Phone')),
                ('chicken_pox', models.CharField(choices=[('IMM', 'IMMUNE'), ('NIM', 'NOT IMMUNE')], max_length=20)),
                ('measles', models.CharField(choices=[('IMM', 'IMMUNE'), ('NIM', 'NOT IMMUNE')], max_length=20)),
                ('had_hep_b', models.BooleanField(verbose_name='Had Hapatitis B?')),
                ('medical_p_list', models.TextField(verbose_name='Medical Problems')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hospitaldb.hospital')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['first_name'],
            },
        ),
        migrations.AddField(
            model_name='doctoroffice',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.hospital'),
        ),
        migrations.AddField(
            model_name='doctoroffice',
            name='office_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_office', to=settings.AUTH_USER_MODEL, verbose_name='Office Owner'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('hod', models.CharField(max_length=300)),
                ('department_id', models.CharField(max_length=12)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitaldb.block')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.hospital'),
        ),
    ]
