# Generated by Django 3.0.5 on 2021-01-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0003_auto_20210118_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('hod', models.CharField(max_length=300)),
                ('department_id', models.CharField(max_length=12)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitaldb.Block')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital')),
            ],
        ),
    ]
