# Generated by Django 3.0.5 on 2021-01-18 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitaldb', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_consultation_fee', models.FloatField()),
                ('follow_up_cons_fee', models.FloatField()),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital')),
                ('office_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Doctor's Office",
                'verbose_name_plural': 'Doctor Offices',
            },
        ),
        migrations.CreateModel(
            name='OfficeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_available', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availability', models.CharField(choices=[('AV', 'Available'), ('UA', 'Unavailable')], default=('AV', 'Available'), max_length=2)),
                ('reason_for_unavailability', models.CharField(max_length=2000)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.DoctorOffice')),
            ],
            options={
                'verbose_name': "Doctor's Schedule",
                'verbose_name_plural': 'Doctors Schedule',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('em_cont_name', models.CharField(max_length=150, verbose_name='Emergency Contact Name')),
                ('em_cont_hm_ph', models.CharField(max_length=20, verbose_name='Emergency Conatact Home Phone')),
                ('em_cont_add', models.CharField(max_length=250, verbose_name='Emergency Contact Address')),
                ('em_cont_wrk_ph', models.CharField(max_length=250, verbose_name='Emergency Contact Work Phone')),
                ('chicken_pox', models.CharField(choices=[('IMM', 'IMMUNE'), ('NIM', 'NOT IMMUNE')], max_length=20)),
                ('measles', models.CharField(choices=[('IMM', 'IMMUNE'), ('NIM', 'NOT IMMUNE')], max_length=20)),
                ('had_hep_b', models.BooleanField(verbose_name='Had Hapatitis B?')),
                ('medical_p_list', models.TextField(verbose_name='Medical Problems')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hospitaldb.Hospital')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
