# Generated by Django 3.0.5 on 2021-01-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0005_doctoroffice_medicalrecord_officeschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['first_name'], 'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('nurse_id', models.CharField(max_length=7, unique=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital')),
            ],
        ),
    ]
