# Generated by Django 3.0.5 on 2021-01-21 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitaldb', '0007_auto_20210121_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoroffice',
            name='officeowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Office Owner'),
        ),
    ]
