# Generated by Django 3.0.5 on 2021-01-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0008_auto_20210121_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoroffice',
            old_name='officeowner',
            new_name='office_owner',
        ),
        migrations.AddField(
            model_name='doctoroffice',
            name='office_name',
            field=models.CharField(default='Office Name', max_length=400),
            preserve_default=False,
        ),
    ]
