# Generated by Django 3.1.7 on 2021-04-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0012_auto_20210125_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officeschedule',
            name='reason_for_unavailability',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
