# Generated by Django 3.2 on 2021-04-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Feature Name')),
                ('summary', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('AS', 'Active State'), ('BS', 'Beta State')], default=('BS', 'Beta State'), max_length=50, verbose_name='Feature State')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sponsor Name')),
                ('logo', models.URLField()),
                ('website_url', models.URLField(verbose_name='Website URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaticSiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('app_name', models.CharField(max_length=150, verbose_name='Application Name')),
                ('app_summary', models.CharField(max_length=500, verbose_name='Application Summary')),
                ('tag_line', models.CharField(max_length=500, verbose_name='Tag Line')),
                ('date_founded', models.DateField(verbose_name='Date Founded')),
                ('current_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Website Information',
                'verbose_name_plural': 'Static Website Informations',
            },
        ),
    ]
