# Generated by Django 3.0.5 on 2021-01-18 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitaldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Full Name')),
                ('doctor_id', models.CharField(max_length=10, unique=True, verbose_name='Doctors ID')),
                ('practicing_from', models.DateField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('home_address', models.CharField(max_length=200, verbose_name='Home Address')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('family_or_emerg_phone', models.CharField(blank=True, max_length=20, verbose_name='Family or Emergency Phone Number')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization', models.ManyToManyField(to='accounts.Specialization')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
            ],
            options={
                'verbose_name': "Doctor's Specialization",
                'verbose_name_plural': "Doctor's Specialization(s)",
                'ordering': ['doctor'],
            },
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=700, verbose_name='Qualification Name')),
                ('institute_name', models.CharField(max_length=700, verbose_name='Name Of Institution')),
                ('procurement_year', models.DateField(verbose_name='Precurment Date in YYY-MMM-DDD')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
            ],
            options={
                'verbose_name': "Doctor's Qualification",
                'ordering': ['doctor'],
            },
        ),
    ]
