# Generated by Django 3.0.5 on 2021-01-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0004_department'),
        ('accounts', '0003_auto_20210118_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='residing_hospital',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital'),
        ),
    ]
