# Generated by Django 3.0.5 on 2021-02-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_doctor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default='username-slug', unique=True),
            preserve_default=False,
        ),
    ]
