# Generated by Django 3.0.5 on 2021-03-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210227_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreview',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientreview',
            name='not_recommended_reason',
            field=models.TextField(blank=True, max_length=2000, verbose_name='A Reason for not recommending this Doctor'),
        ),
    ]
