# Generated by Django 3.0.5 on 2021-01-26 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitaldb', '0012_auto_20210125_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Full Name')),
                ('doctor_id', models.CharField(max_length=10, unique=True, verbose_name='Doctors ID')),
                ('practicing_from', models.DateField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('residing_hospital', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=500)),
                ('account_name', models.CharField(max_length=350)),
                ('account_number', models.CharField(max_length=11)),
                ('branch_name', models.CharField(max_length=300)),
                ('branch_code', models.CharField(max_length=6)),
                ('swift_code', models.CharField(max_length=8)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PatientReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(max_length=500, verbose_name='The review name or summary')),
                ('is_review_anonymous', models.BooleanField(default=False)),
                ('wait_time_rating', models.FloatField(blank=True, max_length=3)),
                ('bedside_manner_rating', models.FloatField(blank=True, max_length=3)),
                ('overall_rating', models.FloatField(max_length=5)),
                ('review', models.TextField(blank=True, max_length=4000)),
                ('is_doctor_recommended', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=('Y', 'Yes'), max_length=1)),
                ('not_recommended_reason', models.TextField(max_length=2000, verbose_name='A Reason for not recommending this Doctor')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
            options={
                'ordering': ['review_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientInsurranceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurrance_company', models.CharField(max_length=500)),
                ('insurrance_name', models.CharField(max_length=300)),
                ('insurrance_account_name', models.CharField(max_length=300)),
                ('insurrance_account_no', models.CharField(max_length=12)),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.PatientBankDetail')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inssurance_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('home_address', models.CharField(max_length=200, verbose_name='Home Address')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('family_or_emerg_phone', models.CharField(blank=True, max_length=20, verbose_name='Family or Emergency Phone Number')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ManyToManyField(to='account.Specialization')),
            ],
            options={
                'verbose_name': "Doctor's Specialization",
                'verbose_name_plural': "Doctor's Specialization(s)",
                'ordering': ['doctor'],
            },
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=700, verbose_name='Qualification Name')),
                ('institute_name', models.CharField(max_length=700, verbose_name='Name Of Institution')),
                ('procurement_year', models.DateField(verbose_name='Precurment Date in YYY-MMM-DDD')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Doctor's Qualification",
                'ordering': ['doctor'],
            },
        ),
        migrations.CreateModel(
            name='AffiliatedHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('affiliation_relationship', models.CharField(help_text='What relationship do have with the hospital, what do you do there', max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('affiliated_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_hospitals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
