# Generated by Django 3.0.5 on 2021-02-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['residing_hospital']},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='affiliatedhospital',
            name='affiliation_relationship',
            field=models.CharField(help_text='What relationship do have with the hospital, what do you or did you do there?', max_length=500),
        ),
    ]
