# Generated by Django 3.2 on 2021-04-20 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('hospitaldb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreview',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='reviewed_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.doctor'),
        ),
        migrations.AddField(
            model_name='patientinsurancedetail',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.patientbankdetail'),
        ),
        migrations.AddField(
            model_name='patientinsurancedetail',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inssurance_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientbankdetail',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorspecialization',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorspecialization',
            name='specialization',
            field=models.ManyToManyField(to='account.Specialization'),
        ),
        migrations.AddField(
            model_name='doctorqualification',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_qualifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='residing_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.hospital'),
        ),
        migrations.AddField(
            model_name='affiliatedhospital',
            name='affiliated_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_hospitals', to=settings.AUTH_USER_MODEL),
        ),
    ]
