# Generated by Django 3.0.5 on 2021-02-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_patient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(default='doctor-username', unique=True),
            preserve_default=False,
        ),
    ]
