# Generated by Django 3.0.5 on 2021-02-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0012_auto_20210125_0704'),
        ('account', '0005_doctor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='residing_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital'),
        ),
    ]
