# Generated by Django 3.0.5 on 2021-02-26 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_auto_20210225_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations', to=settings.AUTH_USER_MODEL),
        ),
    ]
