# Generated by Django 3.0.5 on 2021-02-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210227_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinsurrancedetail',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.PatientBankDetail'),
        ),
    ]
