# Generated by Django 3.0.5 on 2021-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210227_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientreview',
            old_name='is_review_anonymous',
            new_name='anonymous_review',
        ),
        migrations.AddField(
            model_name='patientreview',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='review_state',
            field=models.CharField(choices=[('PUB', 'Published'), ('DFT', 'Draft')], default='PUB', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientreview',
            name='is_doctor_recommended',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=5),
        ),
    ]
