# Generated by Django 3.1.7 on 2021-04-02 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0011_auto_20210305_0904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientInsurranceDetail',
            new_name='PatientInsuranceDetail',
        ),
        migrations.RenameField(
            model_name='patientinsurancedetail',
            old_name='insurrance_account_name',
            new_name='insurance_account_name',
        ),
        migrations.RenameField(
            model_name='patientinsurancedetail',
            old_name='insurrance_account_no',
            new_name='insurance_account_no',
        ),
        migrations.RenameField(
            model_name='patientinsurancedetail',
            old_name='insurrance_company',
            new_name='insurance_company',
        ),
        migrations.RenameField(
            model_name='patientinsurancedetail',
            old_name='insurrance_name',
            new_name='insurance_name',
        ),
    ]
