# Generated by Django 3.2 on 2021-05-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
