# Generated by Django 3.2 on 2021-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='YYY-MMM-DDD', verbose_name='Date Of Birth'),
        ),
    ]
