# Generated by Django 3.0.5 on 2021-01-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0002_auto_20210120_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='YYY-MMM-DDD', verbose_name='Users Date Of Birth'),
        ),
    ]
