# Generated by Django 3.0.5 on 2021-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0003_auto_20210120_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('PT', 'Patient'), ('DR', 'Doctor')], default=('PT', 'Patient'), max_length=10),
        ),
    ]
