# Generated by Django 3.2 on 2021-05-05 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0004_alter_user_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='YYY-MMM-DDD', null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, max_length=300, unique=True, verbose_name='Username'),
        ),
    ]
