# Generated by Django 3.0.5 on 2021-01-26 06:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0004_auto_20210121_1407'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('patient_users', django.db.models.manager.Manager()),
            ],
        ),
    ]
