# Generated by Django 3.0.5 on 2021-01-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0005_auto_20210126_0711'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
