# Generated by Django 3.2 on 2021-05-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0005_auto_20210505_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
