# Generated by Django 3.2 on 2021-05-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0006_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Username'),
        ),
    ]
