# Generated by Django 3.1.7 on 2021-04-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authend', '0006_auto_20210126_2138'),
    ]

    operations = [
    ]
