# Generated by Django 3.2 on 2021-05-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0007_alter_user_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('RNS', 'Rather Not Say')], default='M', max_length=7),
        ),
    ]
