# Generated by Django 3.2 on 2021-05-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authend', '0009_auto_20210507_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
