from .patient_views import PatientProfileAPIView, PatientBankDetailAPI, PatientIsurranceDetailAPI, PatientReviewAPI
from .doctor_views import DoctorProfileAPIView, DoctorQualificationAPI, DoctorSpecializationAPI
