# Generated by Django 2.2.17 on 2020-12-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(blank=True, max_length=100)),
                ('block_floor', models.IntegerField()),
                ('block_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter hospital name', max_length=300)),
                ('address', models.CharField(help_text='hospital address', max_length=450)),
                ('hospital_type', models.CharField(choices=[('SC', 'Special Clinic'), ('TH', 'Tranditional Hospital')], max_length=30)),
                ('rank', models.CharField(choices=[('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5)], max_length=20)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('treatment', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(blank=True, max_length=250)),
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('AV', 'Available'), ('UA', 'Unavailable')], max_length=15)),
                ('slug', models.SlugField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Block')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital')),
            ],
            options={
                'verbose_name': 'Hospital Room',
                'verbose_name_plural': 'Hospital Rooms',
                'ordering': ['availability'],
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=250)),
                ('registered', models.BooleanField(default=True)),
                ('current_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('cert_date', models.DateField(verbose_name='Certification Date')),
                ('cert_exp', models.DateField(verbose_name='Certification Expires')),
                ('trained_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Speciality')),
                ('works_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('appointment_for', models.CharField(max_length=450)),
                ('start_dt_time', models.DateTimeField(verbose_name='start date and time')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Doctor')),
            ],
            options={
                'ordering': ['start_dt_time'],
            },
        ),
    ]
