# Generated by Django 2.2.17 on 2020-12-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(blank=True, max_length=100)),
                ('block_floor', models.IntegerField()),
                ('block_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter hospital name', max_length=300)),
                ('address', models.CharField(help_text='hospital address', max_length=450)),
                ('hospital_type', models.CharField(choices=[('SC', 'Special Clinic'), ('TH', 'Tranditional Hospital')], max_length=30)),
                ('rank', models.CharField(choices=[(1, 'ONE STAR'), (2, 'TWO STAR'), (3, 'THREE STAR'), (4, 'FOUR STAR'), (5, 'FIVE STAR')], max_length=20)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(max_length=250)),
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('AV', 'Available'), ('UA', 'Unavailable')], max_length=15)),
                ('slug', models.SlugField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Block')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital')),
            ],
            options={
                'verbose_name': 'Hospiatal Room',
                'verbose_name_plural': 'Hospital Rooms',
                'ordering': ['availability'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital'),
        ),
    ]
