# Generated by Django 2.2.17 on 2020-12-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hospital',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital'),
        ),
    ]
