# Generated by Django 2.2.17 on 2020-12-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0002_auto_20201208_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='hospital',
        ),
    ]
