# Generated by Django 2.2.17 on 2020-12-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0003_remove_block_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Hospital'),
            preserve_default=False,
        ),
    ]
