# Generated by Django 3.1.4 on 2020-12-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0004_block_hospital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['availability'], 'verbose_name': 'Hospital Room', 'verbose_name_plural': 'Hospital Rooms'},
        ),
    ]
