# Generated by Django 3.1.4 on 2020-12-08 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0005_auto_20201208_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('treatment', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=500)),
                ('cert_date', models.DateField(verbose_name='Certification Date')),
                ('cert_exp', models.DateField(verbose_name='Certification Expires')),
                ('trained_in', models.ManyToManyField(to='hospitaldb.Speciality')),
                ('works_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.hospital')),
            ],
        ),
    ]
