# Generated by Django 3.1.4 on 2020-12-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0006_doctor_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=250)),
                ('registered', models.BooleanField(default=True)),
                ('current_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.hospital')),
            ],
        ),
    ]
