# Generated by Django 3.1.4 on 2020-12-08 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('hospitaldb', '0007_nurse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField()),
                ('appointment_for', models.CharField(max_length=450)),
                ('start_dt_time', models.DateTimeField(verbose_name='start date and time')),
                ('end_dt_time', models.DateTimeField(verbose_name='end date and time')),
                ('examination_room', models.CharField(max_length=450)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.doctor')),
                ('prep_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.nurse')),
            ],
        ),
    ]
