# Generated by Django 3.1.4 on 2020-12-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0010_auto_20201209_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
