# Generated by Django 2.2.17 on 2020-12-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0011_auto_20201210_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['start_dt_time']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='prep_nurse',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='position',
        ),
        migrations.AddField(
            model_name='appointment',
            name='emergency_contact',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
