# Generated by Django 2.2.17 on 2020-12-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0012_auto_20201210_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='slug',
        ),
    ]
