# Generated by Django 2.2.17 on 2020-12-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0013_auto_20201210_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='trained_in',
        ),
        migrations.AddField(
            model_name='doctor',
            name='trained_in',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.Speciality'),
            preserve_default=False,
        ),
    ]
