# Generated by Django 2.2.17 on 2020-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0014_auto_20201211_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_dt_time',
            field=models.DateTimeField(blank=True, verbose_name='end date and time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='examination_room',
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
