# Generated by Django 2.2.17 on 2020-12-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldb', '0015_auto_20201211_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_dt_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='examination_room',
        ),
    ]
