# Generated by Django 3.1.4 on 2020-12-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitaldb', '0007_nurse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('pcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitaldb.doctor')),
            ],
        ),
    ]
