# Generated by Django 3.1.4 on 2020-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='family_phone',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
