# Generated by Django 2.2.17 on 2020-12-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_family_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pcp',
        ),
    ]
