# Generated by Django 2.2.17 on 2020-12-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patient_pcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='family_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
