# Generated by Django 2.2.17 on 2020-12-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticAppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('app_name', models.CharField(max_length=150)),
                ('webapp_url', models.URLField(max_length=50)),
                ('date_founded', models.DateField()),
                ('logo', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Static Application Information',
                'verbose_name_plural': 'Static Application Informations',
            },
        ),
    ]
