# Generated by Django 2.2.17 on 2020-12-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticappinfo',
            name='logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
