# Generated by Django 2.2.17 on 2020-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20201213_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticappinfo',
            name='tagline',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
